### ISSUE TITLE
Footer div of website doesnt have color!

### ISSUE THREAD

**Issue by SlushYEs** [SlushYEs/HactoberFest-2022#11]
the footer div of the website isnt getting color added even after updating styles.css! Work on it and add a matching theme color.

**Comment by heza-ru** [comment]
can i work on this?

**Comment by SlushYEs** [comment]
> can i work on this?

Sure!

**Comment by awantikamallick** [comment]
Could you please assign me this?

**Comment by SlushYEs** [comment]
> Could you please assign me this?

Sure

**Comment by heza-ru** [comment]
so i looked into it and your footer does not have a background-color property and your body doesnt either do you want me to add them?

**Comment by SlushYEs** [comment]
> so i looked into it and your footer does not have a background-color property and your body doesnt either do you want me to add them? The div element for the footer also has some margin so i suggest putting colour on body instead or enclose it into another div instead

I want the colour of footer to be different from the middle so if thats possible then great!

**Comment by SlushYEs** [comment]
> Could you please assign me this?

Hey you might wanna work on another issue. This one's been pretty much fixed

**Comment by Arunkumar-60** [comment]
I can work on this task. please assign me this task

**Comment by Arunkumar-60** [comment]
and please do mention what kind of links do u wanna add to the footer section
